<bar> ::= <note> <note> <note> <note>
<note> ::= <name><octave>4 | <name>4
<name> ::= "a" | "ais" | "aes"  | "b" | "bis" | "bes"  | "c" | "cis" | "ces"  | "d" | "dis" | "des"  | "e" | "eis" | "ees"  | "f" | "fis" | "fes"  | "g" | "gis" | "ges"  |
<octave> ::= "," | "'"